spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/helppoint-product?useTimezone=true&serverTimezone=UTC
    username: root
    password: 142532
  jpa:
    show-sql: true
    hibernate.format_sql: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/