spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.40.22:3306/helppoint-product?useTimezone=true&serverTimezone=UTC
    username: root
    password: 142532
  jpa:
    show-sql: true
    hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  zipkin:
    baseUrl: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


