spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://helppoint-mysql:3306/helppoint-product
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
  zipkin:
    baseUrl: http://helppoint-zipkin:9411/

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://helppoint-discovery-server:8761/eureka/